---
title: "Random Sample Generation"
author: "Annika Kuelpmann"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup}
#| include: false

knitr::opts_chunk$set(echo = TRUE)

```

### R Packages used 
```{r packages}
#| message: false

library(tidyverse)
library(readxl)

```

```{r housekeeping}
#| include: false

# IF YOU RUN THIS CODE PLEASE INSERT YOUR FILE PATH ACCORDINGLY 

# set working directory
setwd("{FILE_PATH}")

# import data 
data <- read_csv("{FILE_PATH}") 

```

### Sample: Test Data 
```{r test_sample}

# select relevant data
# remove NAs 
data <- data %>%
  select(ResponseId, trial, text) %>%
  na.omit()

# create data groups related to trial types
# trials with narratives related to future events
future <- c("response1", "response3", "response5", 
                        "response7", "response9", "response11")
# trials with narratives related to past events
past <- c("response2", "response4", "response6", 
                        "response8", "response10", "response12")

# add new variable for groups
data <- data %>%
  mutate(group = ifelse(trial %in% future, "future", "past"))

# get random sample for testing 
# this contains an even number of data sets for past and future events
set.seed(42)
random_sample <- data %>%
  group_by(group) %>%
  slice_sample(n = 60)

```

### Sample: Training Data
```{r training_sample}

# get random sample for training 
# data are not part of the random sample for testing
training_sample <- data %>%
  anti_join(random_sample, by = "ResponseId") %>%  
  group_by(group) %>%
  slice_sample(n = 10)

```

### Save Samples 
```{r saving}

# IF YOU RUN THIS CODE PLEASE INSERT YOUR FILE PATH ACCORDINGLY 

# save test data as csv-file
write_csv(random_sample, "{FILE_PATH}")

# save training data as csv-file
write_csv(training_sample, "{FILE_PATH}")

```

